// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "mongodb+srv://gus:11j7q6aZ3pmqqOUb@cluster0.n6rxh.mongodb.net/godofredo"
  },
});
